server:
  port: 8080  # 메인 애플리케이션 포트

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: lunch-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Swagger UI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
    enabled: true
  api-docs:
    path: /api-docs
  packages-to-scan: com.example.lunchWithMe.controller